[package]
name = "server_concurrent"
version.workspace = true
default-run = "server"
edition.workspace = true
publish.workspace = true

[dependencies]
tokio = { workspace = true, features = ["io-std", "io-util", "macros", "net", "rt", "rt-multi-thread"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
